---
title: "Total Deaths"
output: html_notebook
---

```{r Setup, message = FALSE, warning = FALSE}
library(tidyverse)
library(dplyr)
library(utils)
library(lubridate)
library(ggplot2)
library(ggrepel)
```

#Read raw data for deaths
```{r}
deaths <- read.csv("https://raw.githubusercontent.com/dsfsi/covid19za/master/data/covid19za_provincial_cumulative_timeline_deaths.csv", na.strings = "", fileEncoding = "UTF-8-BOM", stringsAsFactors = TRUE)
deaths
```

#Write raw data
```{r}
write.csv(deaths, "data/data_raw/raw_02_total_deaths.csv")
```

```{r}
covid <- deaths %>% 
  mutate(date = dmy(date),
         deaths = total) %>% 
  select(date, deaths)
covid
```

#Read raw data for cases
```{r}
cases <- read.csv("https://raw.githubusercontent.com/dsfsi/covid19za/master/data/covid19za_provincial_cumulative_timeline_confirmed.csv", na.strings = "", fileEncoding = "UTF-8-BOM", stringsAsFactors = TRUE)
cases
```

#Cases
```{r}
covid1 <- cases %>% 
  mutate(date = dmy(date),
         cases = total) %>% 
  select(date, cases)
covid1
```

```{r}
covid2 <- covid1 %>% 
  left_join(covid, by = c("date" = "date"))
covid2
```

#Create Case Fatality Rate data
```{r}
covid3 <- covid2 %>% 
  filter(deaths >= 1) %>% 
  mutate(case_fatality_rate = (deaths / cases)*100) %>% 
  select(date, deaths, case_fatality_rate)
covid3
```

#Write to data_out folder
```{r}
saveRDS(covid3, "data/data_out/02_total_deaths.rds")
write.csv(covid3, "data/data_out/02_total_deaths.csv")
```

```{r}
plot1 <- covid3 %>% 
  mutate(label = if_else(date == max(date), as.character(formatC(as.integer(deaths), big.mark = ",")), NA_character_)) %>% 
  ggplot(aes(date, deaths)) + expand_limits(y = c(0, 1500)) + geom_line(color = "red") + geom_label_repel(aes(label = label), color = "white",fill = "#203354", segment.colour = "black", fontface = "bold", na.rm = TRUE, label.size = NA, box.padding = unit(-0.5, "lines"))
```


```{r}
plot2 <- ggplot() +
  data = covid3 +
  aes(date, case_fatality_rate) +
  ylim(0.10) +
  geom_point(colour = "grey") +
  theme_minimal()
```

```{r}
g1 <- ggplot_gtable(ggplot_build(plot1))
g2 <- ggplot_gtable(ggplot_build(plot2))
```

```{r}
pp <- c(subset(g1$layout,
               name == "panel",
               se = t:r))

g <- gtable_add_grob(g1, 
                     g2$grobs[[which(g2$layout$name == "panel")]],
                     pp$t,
                     pp$l,
                     pp$b,
                     pp$l)
```

```{r}
ia <- which(g2$layout$name == "axis-l")
ga <- g2$grobs[[ia]]
ax <- ga$children[[2]]
ax$widths <- rev(ax$widths)
ax$grobs <- rev(ax$grobs)
ax$grobs[[1]]$x <- ax$grobs[[1]]$x - unit(1, "npc") + unit(0.15, "cm")
g <- gtable_add_cols(g, g2$widths[g2$layout[ia, ]$l], length(g$widths) - 1)
g <- gtable_add_grob(g, ax, pp$t, length(g$widths) - 1, pp$b)

grid.draw(g)
```



```{r}
plot <- ggplot() + 
  geom_line(data = covid3, 
            aes(x = date, 
                y = deaths), 
            color = "#b54c49") +
  geom_line(data = covid3, 
            aes(x = date, 
                y = case_fatality_rate), 
            color = "#969da1",
            linetype = "dashed") +
  scale_y_continuous(name = NULL,
                     breaks = seq(0, 2400, by = 200), 
                     sec.axis = sec_axis(~./20000*100))+
                                         #labels = function(b) { paste0(round(b * 100, 0), "%")})) +
                                         #labels = scales::percent_format(accuracy = 1)))+
                                         #name = NULL,
                                        # breaks = seq(0, 10, by = 1))) +
  #labels = scales::percent_format(accuracy = 1),
                    #sec.axis = sec_axis(~., name = NULL))
  scale_x_date(date_labels = "%d/%m",date_breaks = "1 month") +
  labs(x = NULL,
       y = NULL, 
       title = "Total Deaths",
       caption = "Updated: 16 June 2020") +
  theme_minimal() + 
  theme(legend.position = "bottom",
        panel.grid.minor.x = element_blank(), 
        axis.text.x = element_text(size = 11, color = "#969da1"),
        axis.text.y = element_text(size = 11, color = "#969da1"),
        plot.title = element_text(face = "bold", size = rel(1.5), hjust = 0.0, colour = "white"), 
        plot.caption = element_text(size = 11, hjust = 0, face = "bold", color = "white"),
        plot.background = element_rect(size = 1.5, fill = "#142c44", colour = "#969da1"),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        panel.border = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.line = element_blank())
plot 
```























