---
title: "Deaths by Province"
output: html_notebook
---

```{r Setup, message = FALSE, warning = FALSE}
library(tidyverse)
library(dplyr)
library(utils)
library(lubridate)
library(ggplot2)
```

#Read raw CSV data
```{r}
data <- read.csv("https://raw.githubusercontent.com/dsfsi/covid19za/master/data/covid19za_provincial_cumulative_timeline_deaths.csv", na.strings = "", fileEncoding = "UTF-8-BOM", stringsAsFactors = TRUE)
data
```

#Write raw data
```{r}
write.csv(data, "data/data_raw/raw_03_deaths_by_province.csv")
```

#Pivot longer data
```{r}
new <- data %>% 
  pivot_longer(c('EC', 'FS','GP', 'KZN', 'LP', 'MP', 'NC', 'NW', 'WC',), names_to = "province", values_to = "deaths")
new
```

#Only show data for date, provinces and deaths
```{r}
covid <- new %>% 
  select(date, province, deaths) %>% 
  mutate(date = dmy(date)) %>% 
  filter(date == max(date)) %>% 
  mutate(province = factor(province, levels = c("WC","EC", "KZN", "GP", "FS", "LP", "NC", "NW", "MP"))) %>% 
  arrange(province)
covid
```

#Write to data_out folder
```{r}
saveRDS(covid, "data/data_out/03_total_deaths_by_province.rds")
write.csv(covid, "data/data_out/03_total_deaths_by_province.csv")
```

```{r}
plot <- ggplot(data = covid,
               mapping = aes(x = reorder(province, -deaths),
                             y = deaths)) +
  geom_bar(stat = "identity",
           width = 0.9,
           fill = "#b54c49",
           color = "#b54c49") +
  geom_text(aes(label = deaths), 
            colour = "white", 
            position = position_dodge(width = 1.0), 
            hjust = + 0.50, 
            vjust = - 0.50) +
  labs(x = NULL, 
       y = NULL, 
       title = "Deaths by Province",
       caption = "Updated: 16 June 2020") +
  theme_minimal() +
  theme(panel.grid.minor.x = element_blank(), 
        axis.text.x = element_text(size = 11, color = "#969da1"),
        axis.text.y = element_blank(),
        plot.title = element_text(face = "bold", size = rel(1.5), hjust = 0.0, colour = "white"), 
        plot.caption = element_text(size = 11, hjust = 0, color = "white"),
        plot.background = element_rect(size = 1.5, fill = "#142c44", colour = "#969da1"),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        panel.border = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.line = element_blank())
plot
```











