---
title: "Daily infection increases from first 100"
output: html_notebook
---


```{r Setup, message = FALSE, warning = FALSE}
library(tidyverse)
library(dplyr)
library(utils)
library(lubridate)
library(ggplot2)
```

```{r}
data <- read.csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv", na.strings = "", fileEncoding = "UTF-8-BOM")
data
```

```{r}
covid <- data %>% 
  mutate(country = location,
         infections = total_cases,
         date = ymd(date)) %>% 
  filter(total_cases >= 100, country == "South Africa" | country == "United States" | country == "Brazil" | country == "Russia" | country == "United Kingdom" | country == "India" | country == "Italy" | country == "China" | country == "Sweden" |  country == "Singapore" | country == "New Zealand") %>% 
  select(date, country, infections)
covid
```

```{r}
covid19 <- covid %>%
  group_by(country) %>% 
  mutate(day = row_number())
covid19
```


```{r eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
plot <- ggplot(data = covid19,
                 mapping = aes(x = day,
                             y = infections,
                             color = country,
                             linetype = country,
                             size = country)) +
  geom_line(aes(group = country)) +
  scale_x_log10() +
  scale_x_continuous(breaks = seq(0, 450, by = 20)) +
  scale_y_continuous(breaks = c(0, 100, 200, 300, 400, 500,  600, 700, 800, 900, 1000, 2000, 3000, 4000, 5000, 6000, 10000, 20000, 30000, 40000)) +
  scale_linetype_manual(values = c("United States" = "dashed", 
                                   "Brazil" = "dashed", 
                                   "Russia" = "dashed", 
                                   "United Kingdom" = "dashed",
                                   "India" = "dashed", 
                                   "Italy" = "dashed", 
                                   "China" = "dashed", 
                                   "South Africa" = "solid", 
                                   "Sweden" = "dashed", 
                                   "Singapore" = "dashed", 
                                   "New Zealand" = "dashed")) +
  scale_colour_manual(values = c("United States" = "#969da1", 
                                 "Brazil" = "#969da1", 
                                 "Russia" = "#969da1", 
                                 "United Kingdom" = "#969da1", 
                                 "India" = "#969da1", 
                                 "Italy" = "#969da1", 
                                 "China" = "#969da1", 
                                 "South Africa" = "#b54c49", 
                                 "Sweden" = "#969da1", 
                                 "Singapore" = "#969da1", 
                                 "New Zealand" = "#969da1")) +
  scale_size_manual(values = c("United States" = 0.5, 
                               "Brazil" = 0.5, 
                               "Russia" = 0.5, 
                               "United Kingdom" = 0.5, 
                               "India" = 0.5, 
                               "Italy" = 0.5, 
                               "China" = 0.5, 
                               "South Africa" = 1.25, 
                               "Sweden" = 0.5, 
                               "Singapore" = 0.5, 
                               "New Zealand" = 0.5)) +
  labs(x = NULL,
       y = NULL,
       title = "Daily infection increases from first 100",
       caption = "Updated: 16 June 2020") + # title label 
  theme_minimal() + # add theme
  theme(legend.title = element_blank(),
        legend.position = c(0.9, 0.2), 
        legend.text = element_text(color = "white"),
        panel.grid.minor.x = element_blank(), 
        axis.text.x = element_text(size = 11, color = "#969da1"),
        axis.text.y = element_text(size = 11, color = "#969da1"),
        plot.title = element_text(face = "bold", size = rel(1.5), hjust = 0.0, colour = "white"), 
        plot.caption = element_text(size = 11, hjust = 0, face = "bold", color = "white"),
        plot.background = element_rect(size = 1.5, fill = "#142c44", colour = "#969da1"),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        panel.border = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.line = element_blank())
plot
```