---
title: "Average Daily Tests Weekly"
output: html_notebook
---

```{r Setup, include=FALSE}
library(tidyverse)
library(readr)
library(utils)
library(rvest)
library(ggplot2)
library(lubridate)

```


```{r echo=TRUE}
media <- read.csv("case_media.csv", na.strings = "", fill = TRUE, header = TRUE, stringsAsFactors = TRUE)
head(media)
```

```{r echo=TRUE}
av_daily <- media %>% 
  mutate(weeks = week_label,
         week_av = round(weekly_tests/7)) %>% 
  select(weeks, weekly_tests, week_av) %>% 
  filter(!is.na(weekly_tests))
av_daily
```

```{r}
av_daily <- av_daily %>% # for labelling purposes
  mutate(week_av = as.integer(week_av),
         weekly_tests1 = formatC(weekly_tests, big.mark = ","),
         week_av1 = formatC(week_av, big.mark = ","))
av_daily
```


# Average daily tests per week
```{r}
week_plot <- ggplot(data = av_daily, 
                    mapping = aes(x = reorder(weeks, -week_av),
                                  y = week_av))+
  geom_bar(stat= "identity",
           width=0.9,
           fill = "#b54c49",
           color = "#b54c49") +
  geom_text(aes(label = week_av1), 
            position=position_dodge(width=0.9),
            size = 3.5,
            vjust = 0.35,
            hjust = -0.15,
            color = "white")+
  labs(x= NULL,
       y = NULL,
       title="Average daily test per week",
       caption = "Updated: 16 June 2020") + 
  theme_minimal() + 
  theme(panel.grid.minor.x = element_blank(), 
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "#969da1", hjust = 1.0, vjust = 0),
        plot.title = element_text(face = "bold", size = rel(1.5), hjust = -0.25, colour = "white"),
        plot.subtitle = element_text(size = 11, color = "#969da1", hjust = -0.50),
        plot.caption = element_text(size = 11, hjust = -0.18, face = "bold", color = "white"),
        plot.background = element_rect(size = 1.5, fill = "#142c44", colour = "#969da1"),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        panel.border = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.line = element_blank())
        
week_plot + coord_flip()
```
#Average daily positives per week

```{r echo=TRUE}
daily_pos <- media %>% 
  mutate(weeks = week_label,
         weekly_case_av = round(weekly_cases/7)) %>% 
  select(weeks,weekly_case_av) %>% 
  filter(!is.na(weekly_case_av))
daily_pos
```

```{r}
daily_pos <- daily_pos %>% # for labelling purposes
  mutate(weekly_case_av1 = formatC(weekly_case_av, big.mark = ","))
daily_pos
```

```{r}
week_p <- ggplot(data = daily_pos, 
                    mapping = aes(x = reorder(weeks,-weekly_case_av),
                                  y = weekly_case_av))+
  geom_bar(stat= "identity",
           width=0.9,
           fill = "#b54c49",
           color = "#b54c49") +
  geom_text(aes(label = weekly_case_av1), 
            position=position_dodge(width=0.9), 
            vjust=-0.2,
            hjust = -0.01,
            color = "white")+
  labs(x= NULL,
       y = NULL,
       title="Average daily positives per week") + 
  theme_minimal() + 
  theme(panel.grid.minor.x = element_blank(), 
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "#969da1", hjust = 1.0, vjust = 0),
        plot.title = element_text(face = "bold", size = rel(1.5), hjust = -0.38, colour = "white"),
        plot.subtitle = element_text(size = 11, color = "#969da1", hjust = -0.50),
        plot.caption = element_text(size = 11, hjust = -0.18, face = "bold", color = "white"),
        plot.background = element_rect(size = 1.5, fill = "#142c44", colour = "#969da1"),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        panel.border = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.line = element_blank())
        
week_p + coord_flip()
```
# No of tests per positive case (weekly)
```{r echo=TRUE}
new_media3 <- media %>% 
  mutate(weeks = week_label) %>% 
  select(weeks,tests_per_case) %>% 
  filter(!is.na(tests_per_case)) 
new_media3
```


```{r}
new_media3 <- new_media3 %>% # for labelling purposes
  mutate(tests_per_case1 = formatC(tests_per_case, big.mark = ","))
new_media3
```

<!-- Needs to be arranged -->
```{r}
week_pos <- ggplot(data = new_media3, 
                    mapping = aes(x = reorder(weeks, -tests_per_case),
                                  y = tests_per_case))+
  geom_bar(stat= "identity",
           width=0.9,
           fill = "#b54c49",
           color = "#b54c49") +
  geom_text(aes(label = tests_per_case1), 
            position=position_dodge(width=0.9), 
            vjust=-0.25,
            hjust = 0.15,
            color = "white")+
  labs(x= NULL,
       y = NULL,
       title="Average daily positives per week") + 
  theme_minimal() + 
  theme(plot.title = element_text(face = "bold", 
                                  size = rel(1.5),
                                  color = "white"), # aspects of the title
        panel.grid = element_blank(),
        axis.text.y = element_text(color = "white"),
        axis.text.x = element_text(color = "white"),
        axis.text.x.bottom = element_blank(),
        plot.background = element_rect(fill = "#142c44", 
                                       color = "blue"),
        plot.caption = element_text(colour = "#969da1"))
        
week_pos + coord_flip()
```










